
runtime: python38

instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
  # Adicione quaisquer outras variáveis ​​de ambiente que você precise aqui
  SECRET_KEY: '@2tcr%p+je0h#+ujlqu*s%ax!$s2%^w9rh%=eg2jv270o3p0+b'
  DEBUG: 'False'
  GUNICORN_CMD_ARGS: "--timeout=1200" # define o tempo limite do trabalhador em 1200 segundos (20 minutos)
automatic_scaling:
  min_instances: 1
  max_instances: 2
  max_concurrent_requests: 50
  max_pending_latency: 30ms
  min_idle_instances: 1
  target_cpu_utilization: 0.5

 

entrypoint: gunicorn -b :8080 wsgi:application



# Install dependencies from requirements.txt
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
  # Add this line to install dependencies

- url: /static
  static_dir: static/

- url: /api/.*
  script: auto



