# Generated by Django 3.2.7 on 2022-08-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_experimentos_original_resultados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentos',
            name='original',
        ),
        migrations.RemoveField(
            model_name='experimentos',
            name='resultados',
        ),
    ]
