# Generated by Django 3.2.7 on 2022-08-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220816_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_experimento', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='documents/')),
                ('numero_repeticoes', models.IntegerField()),
                ('tamanhos_reducao', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
