# Generated by Django 3.2.7 on 2022-08-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_experimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimento',
            name='id_experimento',
        ),
    ]
