# Generated by Django 3.2.7 on 2022-08-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_experimento_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
