# Generated by Django 3.2.7 on 2022-08-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_experimento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
